version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    versioning-strategy: increase
  - package-ecosystem: npm
    directory: '/website'
    schedule:
      interval: daily
    open-pull-requests-limit: 4
    versioning-strategy: increase
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: daily
